# Generated by Django 3.0.3 on 2020-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_userdealers_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
