# Generated by Django 3.0.3 on 2020-09-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicapp', '0003_userprofileinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='dealer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basicapp.UserDealers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userstock',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
